# Generated by Django 3.2.6 on 2022-01-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0003_auto_20220116_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knee',
            name='weight',
        ),
        migrations.AddField(
            model_name='knee',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
