# Generated by Django 3.2.6 on 2022-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0004_auto_20220124_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='knee',
            name='iframe',
            field=models.TextField(blank=True),
        ),
    ]
