# Generated by Django 3.2.6 on 2022-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0005_knee_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knee',
            name='knee_image',
            field=models.ImageField(blank=True, null=True, upload_to='knees'),
        ),
    ]
