# Generated by Django 3.2.6 on 2022-01-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0006_alter_knee_knee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='knee',
            name='mass',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
