# Generated by Django 3.2.6 on 2022-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0007_knee_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='knee',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
