# Generated by Django 3.2.6 on 2022-01-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0019_auto_20220104_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feet',
            name='weight',
        ),
        migrations.AddField(
            model_name='feet',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
